NUM_CLIENTS = 1
NUM_ITERATIONS = 1
INPUT_FILE = "example.wav"
SIMULATE_REALTIME = False
FILE_STREAMING_CHUNK = 1600
FILE_MODE = 'a'

num_chars_printed = 0

num_chars = 3


argument_default = 1600

time_sleep = 0.05